using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._AS.CanvasDesign.UI;

[GenerateTypedNameReferences]
public sealed partial class CanvasDesignPreviewWindow : FancyWindow
{
    public CanvasDesignPreviewWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetPreview(int id, int width, int height, uint background, uint[] pixels, string name, string description)
    {
        Title = Loc.GetString("canvas-design-preview-title-id", ("id", id));
        SignName.Text = name;
        var message = new FormattedMessage();
        if (!message.TryAddMarkup(description, out _))
            message.AddText(description);
        SignDescription.SetMessage(message);
        Canvas.Configure(width, height, background);
        Canvas.SetPixels(pixels);
    }
}
